#pragma checksum "..\..\..\Page\Page_NotChecked.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "12E0F0AFC20ADA21AB9C36940B22BE37F1273D84"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interactivity;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Wpf_Audit;


namespace Wpf_Audit {
    
    
    /// <summary>
    /// Page_NotChecked
    /// </summary>
    public partial class Page_NotChecked : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 35 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker Dp_DebtStart;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker Dp_DebtEnd;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_Export;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid Dg_DebtNotChecked;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel proBar;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock proBarText;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lab_Empty;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_ViewFile;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_DownloadFile;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lab_SaveDirectory;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_Browse;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView Lsv_File;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Check_All;
        
        #line default
        #line hidden
        
        
        #line 171 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu Menu_Style;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel proBarFile;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lab_Exception;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtId;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_Status;
        
        #line default
        #line hidden
        
        
        #line 200 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_Amount;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_ApplyTime;
        
        #line default
        #line hidden
        
        
        #line 208 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtStartTime;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtEndTime;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_BaseInterest;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_RateRatio;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_AdjustTypeName;
        
        #line default
        #line hidden
        
        
        #line 228 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_PayTypeName;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtUnitName;
        
        #line default
        #line hidden
        
        
        #line 236 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_OperatorId;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtTypeName;
        
        #line default
        #line hidden
        
        
        #line 244 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_BondInstituationName;
        
        #line default
        #line hidden
        
        
        #line 248 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_BankName;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_TermClassificationName;
        
        #line default
        #line hidden
        
        
        #line 256 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_CreditUpdateName;
        
        #line default
        #line hidden
        
        
        #line 260 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_IsInGov;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_Remark;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Tbx_Comment;
        
        #line default
        #line hidden
        
        
        #line 282 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_PassItems;
        
        #line default
        #line hidden
        
        
        #line 284 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_RejectItems;
        
        #line default
        #line hidden
        
        
        #line 286 "..\..\..\Page\Page_NotChecked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_SaveItems;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Wpf_Audit;component/page/page_notchecked.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Page\Page_NotChecked.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Dp_DebtStart = ((System.Windows.Controls.DatePicker)(target));
            
            #line 36 "..\..\..\Page\Page_NotChecked.xaml"
            this.Dp_DebtStart.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.Dp_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.Dp_DebtEnd = ((System.Windows.Controls.DatePicker)(target));
            
            #line 39 "..\..\..\Page\Page_NotChecked.xaml"
            this.Dp_DebtEnd.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.Dp_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Btn_Export = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\..\Page\Page_NotChecked.xaml"
            this.Btn_Export.Click += new System.Windows.RoutedEventHandler(this.Btn_Export_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.Dg_DebtNotChecked = ((System.Windows.Controls.DataGrid)(target));
            
            #line 52 "..\..\..\Page\Page_NotChecked.xaml"
            this.Dg_DebtNotChecked.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Dg_DebtNotChecked_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.proBar = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 10:
            this.proBarText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.Lab_Empty = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.Btn_ViewFile = ((System.Windows.Controls.Button)(target));
            
            #line 130 "..\..\..\Page\Page_NotChecked.xaml"
            this.Btn_ViewFile.Click += new System.Windows.RoutedEventHandler(this.Btn_ViewFile_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.Btn_DownloadFile = ((System.Windows.Controls.Button)(target));
            
            #line 136 "..\..\..\Page\Page_NotChecked.xaml"
            this.Btn_DownloadFile.Click += new System.Windows.RoutedEventHandler(this.Btn_DownloadFile_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.Lab_SaveDirectory = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.Btn_Browse = ((System.Windows.Controls.Button)(target));
            
            #line 145 "..\..\..\Page\Page_NotChecked.xaml"
            this.Btn_Browse.Click += new System.Windows.RoutedEventHandler(this.Btn_Browse_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.Lsv_File = ((System.Windows.Controls.ListView)(target));
            
            #line 152 "..\..\..\Page\Page_NotChecked.xaml"
            this.Lsv_File.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.Lsv_File_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 17:
            this.Check_All = ((System.Windows.Controls.CheckBox)(target));
            
            #line 157 "..\..\..\Page\Page_NotChecked.xaml"
            this.Check_All.Click += new System.Windows.RoutedEventHandler(this.Check_All_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.Menu_Style = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 20:
            
            #line 172 "..\..\..\Page\Page_NotChecked.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_View_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 173 "..\..\..\Page\Page_NotChecked.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Download_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.proBarFile = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 23:
            this.Lab_Exception = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.Tbk_DebtId = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.Tbk_Status = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            this.Tbk_Amount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.Tbk_ApplyTime = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 28:
            this.Tbk_DebtStartTime = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 29:
            this.Tbk_DebtEndTime = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.Tbk_BaseInterest = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            this.Tbk_RateRatio = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.Tbk_AdjustTypeName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.Tbk_PayTypeName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.Tbk_DebtUnitName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.Tbk_OperatorId = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.Tbk_DebtTypeName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 37:
            this.Tbk_BondInstituationName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 38:
            this.Tbk_BankName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.Tbk_TermClassificationName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.Tbk_CreditUpdateName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 41:
            this.Tbk_IsInGov = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.Tbk_Remark = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.Tbx_Comment = ((System.Windows.Controls.TextBox)(target));
            return;
            case 44:
            this.Btn_PassItems = ((System.Windows.Controls.Button)(target));
            
            #line 282 "..\..\..\Page\Page_NotChecked.xaml"
            this.Btn_PassItems.Click += new System.Windows.RoutedEventHandler(this.Btn_PassItems_Click);
            
            #line default
            #line hidden
            return;
            case 45:
            this.Btn_RejectItems = ((System.Windows.Controls.Button)(target));
            
            #line 284 "..\..\..\Page\Page_NotChecked.xaml"
            this.Btn_RejectItems.Click += new System.Windows.RoutedEventHandler(this.Btn_RejectItems_Click);
            
            #line default
            #line hidden
            return;
            case 46:
            this.Btn_SaveItems = ((System.Windows.Controls.Button)(target));
            
            #line 286 "..\..\..\Page\Page_NotChecked.xaml"
            this.Btn_SaveItems.Click += new System.Windows.RoutedEventHandler(this.Btn_SaveItems_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 5:
            
            #line 69 "..\..\..\Page\Page_NotChecked.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Click += new System.Windows.RoutedEventHandler(this.Cb_Single_Click);
            
            #line default
            #line hidden
            break;
            case 6:
            
            #line 82 "..\..\..\Page\Page_NotChecked.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Btn_Pass_Click);
            
            #line default
            #line hidden
            break;
            case 7:
            
            #line 84 "..\..\..\Page\Page_NotChecked.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Btn_Reject_Click);
            
            #line default
            #line hidden
            break;
            case 8:
            
            #line 86 "..\..\..\Page\Page_NotChecked.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Btn_Save_Click);
            
            #line default
            #line hidden
            break;
            case 18:
            
            #line 161 "..\..\..\Page\Page_NotChecked.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Click += new System.Windows.RoutedEventHandler(this.Check_Single_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

