#pragma checksum "..\..\Page_Checked.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3C42A52E347A3A6B562392A46467A77E852A1F0B"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interactivity;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Wpf_Audit;


namespace Wpf_Audit {
    
    
    /// <summary>
    /// Page_Checked
    /// </summary>
    public partial class Page_Checked : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 35 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker Dp_DebtStart;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker Dp_DebtEnd;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_Export;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid Dg_DebtChecked;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel proBar;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock proBarText;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lab_Empty;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_View;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_Download;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lab_SaveDirectory;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_Browse;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView Lsv_File;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Check_All;
        
        #line default
        #line hidden
        
        
        #line 149 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu Menu_Style;
        
        #line default
        #line hidden
        
        
        #line 156 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel proBarFile;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lab_Exception;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbx_AuditId;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbx_UserId;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbx_AuditRank;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_Status;
        
        #line default
        #line hidden
        
        
        #line 185 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbx_IsPassed;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbx_DebtId;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_Amount;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_ApplyTime;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtStartTime;
        
        #line default
        #line hidden
        
        
        #line 205 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtEndTime;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_BaseInterest;
        
        #line default
        #line hidden
        
        
        #line 213 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_RateRatio;
        
        #line default
        #line hidden
        
        
        #line 217 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_PayTypeName;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbx_AuditDate;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtUnitName;
        
        #line default
        #line hidden
        
        
        #line 229 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_OperatorId;
        
        #line default
        #line hidden
        
        
        #line 233 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_DebtTypeName;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_BondInstituationName;
        
        #line default
        #line hidden
        
        
        #line 241 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_BankName;
        
        #line default
        #line hidden
        
        
        #line 245 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_TermClassificationName;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_CreditUpdateName;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_IsInGov;
        
        #line default
        #line hidden
        
        
        #line 257 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Tbk_Remark;
        
        #line default
        #line hidden
        
        
        #line 268 "..\..\Page_Checked.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Tbx_Remark;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Wpf_Audit;component/page_checked.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Page_Checked.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Dp_DebtStart = ((System.Windows.Controls.DatePicker)(target));
            
            #line 36 "..\..\Page_Checked.xaml"
            this.Dp_DebtStart.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.Dp_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.Dp_DebtEnd = ((System.Windows.Controls.DatePicker)(target));
            
            #line 39 "..\..\Page_Checked.xaml"
            this.Dp_DebtEnd.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.Dp_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Btn_Export = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\Page_Checked.xaml"
            this.Btn_Export.Click += new System.Windows.RoutedEventHandler(this.Btn_Export_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.Dg_DebtChecked = ((System.Windows.Controls.DataGrid)(target));
            
            #line 52 "..\..\Page_Checked.xaml"
            this.Dg_DebtChecked.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.Dg_DebtChecked_MouseUp);
            
            #line default
            #line hidden
            return;
            case 5:
            this.proBar = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.proBarText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.Lab_Empty = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.Btn_View = ((System.Windows.Controls.Button)(target));
            
            #line 107 "..\..\Page_Checked.xaml"
            this.Btn_View.Click += new System.Windows.RoutedEventHandler(this.Btn_View_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.Btn_Download = ((System.Windows.Controls.Button)(target));
            
            #line 113 "..\..\Page_Checked.xaml"
            this.Btn_Download.Click += new System.Windows.RoutedEventHandler(this.Btn_Download_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.Lab_SaveDirectory = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.Btn_Browse = ((System.Windows.Controls.Button)(target));
            
            #line 122 "..\..\Page_Checked.xaml"
            this.Btn_Browse.Click += new System.Windows.RoutedEventHandler(this.Btn_Browse_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.Lsv_File = ((System.Windows.Controls.ListView)(target));
            
            #line 130 "..\..\Page_Checked.xaml"
            this.Lsv_File.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.Lsv_File_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 13:
            this.Check_All = ((System.Windows.Controls.CheckBox)(target));
            
            #line 135 "..\..\Page_Checked.xaml"
            this.Check_All.Click += new System.Windows.RoutedEventHandler(this.Check_All_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.Menu_Style = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 16:
            
            #line 150 "..\..\Page_Checked.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_View_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 151 "..\..\Page_Checked.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Download_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.proBarFile = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 19:
            this.Lab_Exception = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.Tbx_AuditId = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.Tbx_UserId = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.Tbx_AuditRank = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.Tbk_Status = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.Tbx_IsPassed = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.Tbx_DebtId = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            this.Tbk_Amount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.Tbk_ApplyTime = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 28:
            this.Tbk_DebtStartTime = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 29:
            this.Tbk_DebtEndTime = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.Tbk_BaseInterest = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            this.Tbk_RateRatio = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.Tbk_PayTypeName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.Tbx_AuditDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.Tbk_DebtUnitName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.Tbk_OperatorId = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.Tbk_DebtTypeName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 37:
            this.Tbk_BondInstituationName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 38:
            this.Tbk_BankName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.Tbk_TermClassificationName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.Tbk_CreditUpdateName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 41:
            this.Tbk_IsInGov = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.Tbk_Remark = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.Tbx_Remark = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 14:
            
            #line 139 "..\..\Page_Checked.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Click += new System.Windows.RoutedEventHandler(this.Check_Single_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

